# Generated by Django 4.2.7 on 2025-10-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=20)),
                ('stock', models.CharField(max_length=20)),
            ],
        ),
    ]
