# Generated by Django 4.2.7 on 2025-10-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_product_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Productsnacks',
        ),
    ]
