# Generated by Django 4.2.7 on 2025-10-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_productbeverages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbeverages',
            name='price',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='productvegitable',
            name='price',
            field=models.IntegerField(max_length=20),
        ),
    ]
