# Generated by Django 4.2.7 on 2025-10-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_productbeverages_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productfruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(max_length=20)),
            ],
        ),
    ]
