# Generated by Django 4.2.7 on 2025-10-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='lastnaem',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='staff',
            name='dob',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
