# Generated by Django 4.2.7 on 2025-10-31 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_lastnaem_staff_lastname_staff_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsnacks',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
            preserve_default=False,
        ),
    ]
