# Generated by Django 4.2.7 on 2025-11-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_productsnacks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbeverages',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productfruits',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productsnacks',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productvegitable',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
