# Generated by Django 4.2.7 on 2025-11-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_productbeverages_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsnacks',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productsnacks',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productsnacks',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
