# Generated by Django 4.2.7 on 2025-11-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_productbeverages_user_productbeverages_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbeverages',
            name='liter',
            field=models.CharField(default='liter', max_length=20),
        ),
        migrations.AddField(
            model_name='productfruits',
            name='kg',
            field=models.CharField(default='kg', max_length=50),
        ),
        migrations.AddField(
            model_name='productvegitable',
            name='kg',
            field=models.CharField(default='kg', max_length=50),
        ),
    ]
