# Generated by Django 4.2.7 on 2025-11-01 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_productbeverages_liter_productfruits_kg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('BEVERAGES', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.productbeverages')),
                ('FRUITS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.productfruits')),
                ('SNACKS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.productsnacks')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('VEGITABLES', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.productvegitable')),
            ],
        ),
    ]
