# Generated by Django 4.2.7 on 2025-11-01 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='BEVERAGES',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.productbeverages'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='FRUITS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.productfruits'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='SNACKS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.productsnacks'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='VEGITABLES',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.productvegitable'),
        ),
    ]
