# Generated by Django 4.2.7 on 2025-11-02 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_cart_beverages_alter_cart_fruits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfruits',
            name='USER',
        ),
    ]
