# Generated by Django 4.2.7 on 2025-11-02 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_productfruits_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbeverages',
            name='USER',
        ),
        migrations.RemoveField(
            model_name='productsnacks',
            name='USER',
        ),
        migrations.RemoveField(
            model_name='productvegitable',
            name='USER',
        ),
    ]
