# Generated by Django 4.2.7 on 2025-11-03 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='name',
        ),
    ]
