# Generated by Django 4.2.7 on 2025-11-18 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_response_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('housename', models.CharField(max_length=200)),
                ('landmark', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=10)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
