# Generated by Django 4.2.7 on 2025-11-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.ImageField(max_length=10, upload_to=''),
        ),
    ]
