# Generated by Django 4.2.7 on 2025-11-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='ADDRESS',
        ),
    ]
