# Generated by Django 4.2.7 on 2025-11-19 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
