# Generated by Django 5.2.7 on 2025-11-19 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_orderbeverages_orderfruits_ordersnacks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbeverages',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='orderfruits',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='ordersnacks',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='ordervegitable',
            old_name='created_at',
            new_name='date',
        ),
    ]
