# Generated by Django 5.2.7 on 2025-11-19 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_rename_created_at_orderbeverages_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfruits',
            name='ADDRESS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.address'),
        ),
    ]
