# Generated by Django 5.2.7 on 2025-11-19 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_orderfruits_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbeverages',
            name='ADDRESS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersnacks',
            name='ADDRESS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordervegitable',
            name='ADDRESS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderfruits',
            name='ADDRESS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.address'),
            preserve_default=False,
        ),
    ]
