# Generated by Django 4.2.7 on 2025-11-19 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_orderbeverages_address_ordersnacks_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbeverages',
            name='ADDRESS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.address'),
        ),
        migrations.AlterField(
            model_name='orderfruits',
            name='ADDRESS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.address'),
        ),
        migrations.AlterField(
            model_name='ordersnacks',
            name='ADDRESS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.address'),
        ),
        migrations.AlterField(
            model_name='ordervegitable',
            name='ADDRESS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.address'),
        ),
    ]
