# Generated by Django 4.2.7 on 2025-11-25 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_orderbeverages_status_orderfruits_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=20)),
                ('total_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.address')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_image', models.ImageField(upload_to='order_items/')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.order')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderfruits',
            name='ADDRESS',
        ),
        migrations.RemoveField(
            model_name='orderfruits',
            name='PRODUCT',
        ),
        migrations.RemoveField(
            model_name='orderfruits',
            name='USER',
        ),
        migrations.RemoveField(
            model_name='ordersnacks',
            name='ADDRESS',
        ),
        migrations.RemoveField(
            model_name='ordersnacks',
            name='PRODUCT',
        ),
        migrations.RemoveField(
            model_name='ordersnacks',
            name='USER',
        ),
        migrations.RemoveField(
            model_name='ordervegitable',
            name='ADDRESS',
        ),
        migrations.RemoveField(
            model_name='ordervegitable',
            name='PRODUCT',
        ),
        migrations.RemoveField(
            model_name='ordervegitable',
            name='USER',
        ),
        migrations.DeleteModel(
            name='Orderbeverages',
        ),
        migrations.DeleteModel(
            name='Orderfruits',
        ),
        migrations.DeleteModel(
            name='Ordersnacks',
        ),
        migrations.DeleteModel(
            name='Ordervegitable',
        ),
    ]
