# Generated by Django 4.2.7 on 2025-11-25 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_order_orderitem_remove_orderfruits_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_image',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_beverages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.productbeverages'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_fruits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.productfruits'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_snacks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.productsnacks'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_vegitable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.productvegitable'),
        ),
    ]
