# Generated by Django 4.2.7 on 2025-11-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_remove_orderitem_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_beverages',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_fruits',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_snacks',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_vegitable',
        ),
        migrations.RemoveField(
            model_name='login',
            name='username',
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
