# Generated by Django 5.2.7 on 2025-11-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_alter_login_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='email',
            new_name='username',
        ),
    ]
