# Generated by Django 4.2.7 on 2025-11-29 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_productegg_productfish'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='EGGS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.productegg'),
        ),
        migrations.AddField(
            model_name='cart',
            name='FISH',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.productfish'),
        ),
    ]
