# Generated by Django 4.2.7 on 2025-11-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_cart_eggs_cart_fish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productmilk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('kg', models.CharField(default='litre', max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Productrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('kg', models.CharField(default='kg', max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
