# Generated by Django 5.2.7 on 2025-11-29 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_productmilk_productrice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmilk',
            old_name='kg',
            new_name='litre',
        ),
    ]
