# Generated by Django 5.2.7 on 2025-11-29 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_rename_kg_productmilk_litre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='MILK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.productmilk'),
        ),
        migrations.AddField(
            model_name='cart',
            name='RICE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.productrice'),
        ),
    ]
