# Generated by Django 4.2.7 on 2025-11-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_order_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productegg',
            old_name='price_per_egg',
            new_name='price',
        ),
    ]
