# Generated by Django 4.2.7 on 2025-11-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_rename_price_per_egg_productegg_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='USER',
            new_name='user',
        ),
    ]
