# Generated by Django 4.2.7 on 2025-11-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_rename_user_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='USER',
        ),
    ]
