# Generated by Django 4.2.7 on 2025-11-30 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_rename_user_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ADDRESS',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='STATUS',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='USER',
            new_name='user',
        ),
    ]
