# Generated by Django 4.2.7 on 2025-11-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_rename_address_order_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='ADDRESS',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='STATUS',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='USER',
        ),
    ]
