# Generated by Django 4.2.7 on 2025-12-03 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_rename_address_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='USER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.user'),
        ),
    ]
