# Generated by Django 5.2.7 on 2025-12-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_rename_user_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='USER',
            new_name='user',
        ),
    ]
