# Generated by Django 5.2.7 on 2025-12-04 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='BEVERAGES',
        ),
        migrations.RemoveField(
            model_name='review',
            name='EGGS',
        ),
        migrations.RemoveField(
            model_name='review',
            name='FISH',
        ),
        migrations.RemoveField(
            model_name='review',
            name='FRUITS',
        ),
        migrations.RemoveField(
            model_name='review',
            name='MILK',
        ),
        migrations.RemoveField(
            model_name='review',
            name='RICE',
        ),
        migrations.RemoveField(
            model_name='review',
            name='SNACKS',
        ),
        migrations.RemoveField(
            model_name='review',
            name='VEGITABLES',
        ),
        migrations.AddField(
            model_name='review',
            name='ORDER_ITEM',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.orderitem'),
            preserve_default=False,
        ),
    ]
