# Generated by Django 5.2.7 on 2025-12-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0060_remove_review_beverages_remove_review_eggs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ORDER_ITEM',
        ),
    ]
