# Generated by Django 5.2.7 on 2025-12-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0061_remove_review_order_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
