# Generated by Django 5.2.7 on 2025-12-04 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comt', models.CharField(max_length=100)),
                ('orderitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.orderitem')),
            ],
        ),
    ]
