# Generated by Django 5.2.7 on 2025-12-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0063_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
