# Generated by Django 4.2.7 on 2025-12-05 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0064_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
            preserve_default=False,
        ),
    ]
