# Generated by Django 4.2.7 on 2025-12-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0066_alter_address_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='STATUS',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Prepared', 'Prepared'), ('Confirmed', 'Confirmed'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
