# Generated by Django 4.2.7 on 2025-12-05 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0068_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ORDER_ITEM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='myapp.orderitem'),
        ),
    ]
