# Generated by Django 5.2.7 on 2026-02-19 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0069_alter_review_order_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(default='Requested', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('ORDER_ITEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.orderitem')),
            ],
        ),
    ]
