# Generated by Django 5.2.7 on 2026-02-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0070_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
