from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('login',views.login,name='login'),
    path('user_register', views.user_register, name='user_register'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('verify_otp/', views.verify_otp, name='verify_otp'),
    path('reset_password/', views.reset_password, name='reset_password'),


    path('adminhome',views.adminhome,name='adminhome'),
    path('product_snack',views.product_snack,name='product_snack'),
    path('snack_pageview',views.snack_pageview,name='snack_pageview'),
    path('product_vegitable',views.product_vegitable,name='product_vegitable'),
    path('vegitable_pageview',views.vegitable_pageview,name='vegitable_pageview'),
    path('product_beverages',views.product_beverages,name='product_beverages'),
    path('beverage_pageview',views.beverage_pageview,name='beverage_pageview'),
    path('product_fruits',views.product_fruits,name='product_fruits'),
    path('fruits_pageview',views.fruits_pageview,name='fruits_pageview'),
    path('product_egg',views.product_egg,name='product_egg'),
    path('egg_pageview',views.egg_pageview,name='egg_pageview'),
    path('product_fish',views.product_fish,name='product_fish'),
    path('fish_pageview',views.fish_pageview,name='fish_pageview'),
    path('product_rice',views.product_rice,name='product_rice'),
    path('rice_pageview',views.rice_pageview,name='rice_pageview'),
    path('product_milk',views.product_milk,name='product_milk'),
    path('milk_pageview',views.milk_pageview,name='milk_pageview'),
    path('add_review/<int:id>/', views.add_review, name='add_review'),
    path('admin_update_order', views.admin_update_order, name='admin_update_order'),
    path('place_order', views.place_order, name="place_order"),
    path('order_success', views.order_success, name='order_success'),
    path('orders', views.orders, name='orders'),

    path('return_item/<int:item_id>/', views.return_item, name='return_item'),
    path('track-return/<int:item_id>/', views.track_return, name='track_return'),
    path('staff_update_return_order', views.staff_update_return_order, name='staff_update_return_order'),


    path("update_order_status/<int:order_id>/", views.update_order_status, name="update_order_status"),
    path('cancel_order/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('delete_product_admin/<int:id>/', views.delete_product_admin, name='delete_product_admin'),
    path('delete_product_staff/<int:id>/', views.delete_product_staff, name='delete_product_staff'),
    path('track_order<int:order_id>/', views.track_order, name='track_order'),
    path('staff_update_order',views.staff_update_order,name='staff_update_order'),
    path('staff_register',views.staff_register,name='staff_register'),
    path('staffhome',views.staffhome,name='staffhome'),
    path('shop',views.shop,name='shop'),
    path('snack_cart/<int:id>',views.snack_cart,name='snack_cart'),
    path('vegitable_cart/<int:id>', views.vegitable_cart, name='vegitable_cart'),
    path('fruit_cart/<int:id>', views.fruit_cart, name='fruit_cart'),
    path('beverges_cart/<int:id>', views.beverges_cart, name='beverges_cart'),
    path('egg_cart<int:id>/', views.egg_cart, name='egg_cart'),
    path('fish_cart<int:id>/', views.fish_cart, name='fish_cart'),
    path('rice_cart/<int:id>/', views.rice_cart, name='rice_cart'),
    path('milk_cart/<int:id>/', views.milk_cart, name='milk_cart'),
    path('view_cart', views.view_cart, name='view_cart'),
    path('profile_view', views.profile_view, name='profile_view'),
    path('profile_view_edit<int:id>/', views.profile_view_edit, name='profile_view_edit'),
    path('logout', views.logout, name='logout'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('service', views.service, name='service'),
    path('remove_cart/<int:id>', views.remove_cart, name='remove_cart'),
    path('complaint', views.complaint, name='complaint'),
    path('users_view_admin', views.users_view_admin, name='users_view_admin'),
    path('complaint_view', views.complaint_view, name='complaint_view'),
    path('response', views.response, name='response'),
    path('responde_view_user', views.responde_view_user, name='responde_view_user'),
    path('product_snack_edit<int:id>', views.product_snack_edit, name='product_snack_edit'),
    path('product_vegitable_edit<int:id>', views.product_vegitable_edit, name='product_vegitable_edit'),
    path('product_beverages_edit<int:id>', views.product_beverages_edit, name='product_beverages_edit'),
    path('product_fruits_edit<int:id>', views.product_fruits_edit, name='product_fruits_edit'),
    path('product_egg_edit<int:id>', views.product_egg_edit, name='product_egg_edit'),
    path('product_fish_edit<int:id>', views.product_fish_edit, name='product_fish_edit'),
    path('product_rice_edit<int:id>', views.product_rice_edit, name='product_rice_edit'),
    path('product_milk_edit<int:id>', views.product_milk_edit, name='product_milk_edit'),
    path('staff_view_profile', views.staff_view_profile, name='staff_view_profile'),
    path('staff_admin_view', views.staff_admin_view, name='staff_admin_view'),
    path('checkout', views.checkout, name='checkout'),
    path('add_address', views.add_address, name='add_address'),
    path('increase_qty/<int:item_id>/', views.increase_qty, name='increase_qty'),
    path('decrease_qty/<int:item_id>/', views.decrease_qty, name='decrease_qty'),
    path("search/", views.search, name="search"),
    path("bill/<int:order_id>/", views.bill, name="bill"),
]